version: '3'
services:
    gcloud:
        container_name: hexagoon
        build:
            context: .
        environment:
            OPTIONS: --reload
            PORT: 8000
        ports:
            - "8000:8000"
        volumes:
            - '.:/app'