[default]
root_user = ""
root_email = ""
root_role = "root"
db_driver = ""
db_user = ""
db_address = ""
[production]
root_user = "Fabricio Gatto Lourençone"
root_email = "fabricio@hexsaturn.space"
root_role = "root"
db_driver = "oracle://"
db_user = "ADMIN"
db_address = ""
[development]
root_user = "Fabricio Gatto Lourençone"
root_email = "fabricio@hexsaturn.space"
root_role = "root"
db_driver = "oracle://"
db_user = "ADMIN"
db_address = ""
[testing]
root_user = "Fabricio Gatto Lourençone"
root_email = "fabricio@hexsaturn.space"
root_role = "root"
db_driver = "oracle://"
db_user = "admin"
db_address = ""